apiVersion: monitoring.rhobs/v1
kind: Prometheus
metadata:
  name: metric-storage
  namespace: openstack
spec:
  containers:
  - args:
    - -DFOREGROUND
    command:
    - /usr/sbin/httpd
    image: registry.redhat.io/ubi9/httpd-24@sha256:e91d58021b54c46883595ff66be65882de54abdb3be2ca53c4162b20d18b5f48
    imagePullPolicy: Always
    livenessProbe:
      failureThreshold: 3
      tcpSocket:
        port: 9091
      initialDelaySeconds: 300
      periodSeconds: 30
      successThreshold: 1
      timeoutSeconds: 30
    name: proxy-httpd
    ports:
    - containerPort: 9091
      name: proxy-httpd
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      tcpSocket:
        port: 9091
      initialDelaySeconds: 10
      periodSeconds: 30
      successThreshold: 1
      timeoutSeconds: 30
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/httpd/conf/httpd.conf
      name: httpd-conf
      readOnly: true
      subPath: httpd.conf
    - mountPath: /etc/httpd/conf.d/ssl.conf
      name: httpd-conf
      readOnly: true
      subPath: ssl.conf
    - mountPath: /run/httpd
      name: run-httpd
    - mountPath: /var/log/httpd
      name: log-httpd
    - mountPath: /etc/pki/tls/certs/tls.crt
      name: prometheus-tls-certs
      readOnly: true
      subPath: tls.crt
    - mountPath: /etc/pki/tls/private/tls.key
      name: prometheus-tls-certs
      readOnly: true
      subPath: tls.key
    - mountPath: /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
      name: combined-ca-bundle
      readOnly: true
      subPath: tls-ca-bundle.pem
  volumes:
  - name: httpd-conf
    secret:
      defaultMode: 416
      secretName: prometheus-httpd
  - emptyDir: {}
    name: run-httpd
  - emptyDir: {}
    name: log-httpd
  - name: combined-ca-bundle
    secret:
      defaultMode: 292
      secretName: combined-ca-bundle
  - name: prometheus-tls-certs
    secret:
      defaultMode: 256
      secretName: cert-metric-storage-prometheus-httpd-svc
